###############################################################################
# .github/workflows/tests.yml
#
# NOTE: GitHub Actions does not allocate a TTY, preventing detection of
# piped input using `[[ -t 0 ]]`.
#
# More information:
#
# https://github.com/actions/runner/issues/241
#
# faketty is a GitHub action that uses work-arounds to provide a tty:
#
# https://github.com/marketplace/actions/faketty
#
# Scripts used by faketty for each platform:
#
# linux: `faketty`
#
# ```bash
# #!/bin/bash
#
# script -q -e -c "$*"
# ```
#
# win32: `faketty.ps1`
#
# ```posh
# Invoke-Expression "$args"
# ```
#
# darwin: `faketty`
#
# requires: `brew install expect`
#
# ```bash
# #!/bin/bash
#
# unbuffer $*
# ```
###############################################################################

name: "pb · Test Suite"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  # test-macos-11:
  #   name: "Test: macOS Big Sur 11.0"
  #   runs-on: macos-11.0
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: "Setup"
  #       run: |
  #         brew update
  #         brew install bats-core
  #         brew install expect
  #     - name: "Set $TERM=xterm"
  #       run:  printf "TERM=xterm\\n" >> $GITHUB_ENV
  #     - name: "Run bats tests"
  #       run:  unbuffer bats test
  test-macos-15:
    name: "Test: macOS 15"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: "Setup"
        run: |
          brew update
          brew install bats-core
          brew install expect
      - name: "Set $TERM=xterm"
        run:  printf "TERM=xterm\\n" >> $GITHUB_ENV
      - name: "Run bats tests"
        run:  unbuffer bats test
